version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
