# Check the documentation at http://goreleaser.com
version: 2

builds:
  - skip: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^(build|chore|ci|doc|docs|none|perf|refactor|skip|test)(\\(.*?\\))?:"
release:
  discussion_category_name: General
  prerelease: auto
